### ISSUE TITLE
Tests fail with pytest 9.1: _pytest.monkeypatch.notset removed

### ISSUE THREAD

**Issue by hrnciar** [pallets/flask#6071]
Flask's test suite imports the private notset sentinel from _pytest.monkeypatch in both tests/conftest.py and tests/test_cli.py. pytest 9.1 removed this attribute, moving it to _pytest.compat.NOTSET. This causes a collection-time crash — no tests can run at all.

### Reproducing
```
pip install -e . pytest==9.1.1
pytest tests/
tests/test_cli.py:14: in <module>
    from _pytest.monkeypatch import notset
E   ImportError: cannot import name 'notset' from '_pytest.monkeypatch'
```
Even after fixing test_cli.py, every test fails because tests/conftest.py accesses monkeypatch.notset as a module attribute in the _standard_os_environ session fixture:

`tests/conftest.py:19: AttributeError: module '_pytest.monkeypatch' has no attribute 'notset'`
### Expected Behavior
The test suite should work with pytest 9.1+.

### Environment:

Python version: 3.15.0b2
Flask version: 3.1.3

**Comment by mgorny** [comment]
@davidism, how would you feel if I took the big cannon here and replaced all the private pytest API use? I'm thinking of making `_standard_os_environ` test-scoped and removing `_reset_os_environ` (I don't think the optimization to make it session scoped is really worth it), and making `test_cli` use `delitem(..., raising=False)`.

**Comment by mgorny** [comment]
Actually, I don't really understand why it's done like that. FWIU it first unsets all envvars once, then unsets them after every test… rather than unsetting them before every test?

**Comment by davidism** [comment]
I only vaguely remember implementing all that environ stuff. I'll need to investigate what it was about, there was definitely a reason at the time.

**Comment by mgorny** [comment]
Do you think it would be sufficient that I try if tests pass without it?

**Comment by davidism** [comment]
Yeah, but try on Linux and Windows if you can. I think it might have had to do with running tests while also having an example app running (like when fixing a bug), so `FLASK_APP` was set and messing things up?

**Comment by mgorny** [comment]
Okay, I think I've found the non-obvious difference: the logic as it stands now always restores the environment variables to their original state. Plain `monkeypatch.delenv(...)` only restores the original value if the envvar was set; if it wasn't and the test sets it, it isn't unset afterwards, i.e.:

```python
import os

def test_foo(monkeypatch):
  monkeypatch.delenv("FOO", False)
  os.environ["FOO"] = "bar"

def test_bar():
  assert os.environ.get("FOO") is None
```

will fail if `FOO` is unset, since `test_foo()` will leave it set as `bar`.

That said, the tests are broken anyway, given that they fail if `FOO` is set in the calling environment already, so I'm not sure if cleaning up the environment after the tests setting `FOO` really makes sense. In the end, it only hides the actual issue with other tests relying on `FOO` not being set.

**Comment by davidism** [comment]
Tracked the origin of these fixtures to #2589 and PR #2592. It was because I had an example `FLASK_APP` set in the environment when running the tests, which the tests didn't expect.
