### ISSUE TITLE
Removing json_available reduces backward compatibility

### ISSUE THREAD

**Issue by aadibajpai** [pallets/flask#3288]
### Expected Behavior

json_available should be available

```python
from flask import json_available
```

### Actual Behavior

```pytb
ImportError: cannot import name 'json_available'
```

### Environment

* Python version: 3.7.3
* Flask version: 1.1.0
* Werkzeug version: 0.15.4

**Comment by cygnus2048** [comment]
After upgrading to 1.1.0 I'm now getting this same import error with flask-testing at version of 0.7.1.  For now I will lock to the old version of Flask, but it would be nice to get this fixed.  Thanks.
```    from flask_testing import TestCase
/home/*/.local/lib/python2.7/site-packages/flask_testing/__init__.py:13: in <module>
    from .utils import TestCase, LiveServerTestCase
/home/*/.local/lib/python2.7/site-packages/flask_testing/utils.py:38: in <module>
    from flask import json_available, templating, template_rendered
E   ImportError: cannot import name json_available
```

**Comment by davidism** [comment]
1.1.1 is now available on PyPI.
