### PR TITLE
Fix Blueprint.errorhandler restricts type of result function which avoids chaining

### LINKED ISSUE #4297: Blueprint.errorhandler restricts type of result function which avoids chaining
In flask 2.0.1 it was possible to chain multiple uses of `Blueprint.errorhandler` as a decorator. In 2.0.2 the type of `Blueprint.errorhandler` is too strict to allow this. Let's assume you start out with a plain handler function of type `ErrorHandlerCallable[Exception]` or similar, applying `some_blueprint.errorhandler(SomeExceptionA)` to it, changes the type of the handler to `ErrorHandlerCallable[SomeExceptionA]`. Applying `some_blueprint.errorHandler(SomeExceptionB)` is now no longer possible, because it expects a `ErrorHandlerCallable[SomeExceptionB]` which the existing error handler cannot fullfill.

Consider this example program:

```Python
from flask import Blueprint

blueprint = Blueprint('example', __name__)

class ExceptionA(Exception):
    pass

class ExceptionB(Exception):
    pass

@blueprint.errorhandler(ExceptionB)
@blueprint.errorhandler(ExceptionA)
def error(e):
    return "example"
```

with flask 2.0.1 this typechecked, with flask 2.0.2 I get the following error:

```
$ mypy test.py
test.py:11: error: Argument 1 has incompatible type "ErrorHandlerCallable[ExceptionA]"; expected "ErrorHandlerCallable[ExceptionB]"
Found 1 error in 1 file (checked 1 source file)
```

I would expect this example to work in 2.0.2 just as well as it did in 2.0.1.

I think the semantically most correct way to fix this, would be to to give `errorhandler` a type smilar to `Callable[[SomeOtherGenericException], Callable[[ErrorHandlerCallable[GenericException]], ErrorHandlerCallable[GenericException]]` where `SomeOtherGenericException` would be a type variable that would always need to be a subtype of `GenericException`, but I am not sure if Python's type system can express relations between type variables like that.

Environment:

- Python version: 3.9.7
- Flask version: 2.0.2

### PR DESCRIPTION
**Pull request by Rohan-Salwan**
- fixed #4297 

Checklist:

- [x] I did tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [x] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by davidism** [comment]
This appears to revert the changes from #4097, which were addressing #4095. It also essentially erases all type information, including the number of arguments to the function, which is not an improvement.
