### ISSUE TITLE
Blueprint.errorhandler restricts type of result function which avoids chaining

### ISSUE THREAD

**Issue by Kritzefitz** [pallets/flask#4297]
In flask 2.0.1 it was possible to chain multiple uses of `Blueprint.errorhandler` as a decorator. In 2.0.2 the type of `Blueprint.errorhandler` is too strict to allow this. Let's assume you start out with a plain handler function of type `ErrorHandlerCallable[Exception]` or similar, applying `some_blueprint.errorhandler(SomeExceptionA)` to it, changes the type of the handler to `ErrorHandlerCallable[SomeExceptionA]`. Applying `some_blueprint.errorHandler(SomeExceptionB)` is now no longer possible, because it expects a `ErrorHandlerCallable[SomeExceptionB]` which the existing error handler cannot fullfill.

Consider this example program:

```Python
from flask import Blueprint

blueprint = Blueprint('example', __name__)

class ExceptionA(Exception):
    pass

class ExceptionB(Exception):
    pass

@blueprint.errorhandler(ExceptionB)
@blueprint.errorhandler(ExceptionA)
def error(e):
    return "example"
```

with flask 2.0.1 this typechecked, with flask 2.0.2 I get the following error:

```
$ mypy test.py
test.py:11: error: Argument 1 has incompatible type "ErrorHandlerCallable[ExceptionA]"; expected "ErrorHandlerCallable[ExceptionB]"
Found 1 error in 1 file (checked 1 source file)
```

I would expect this example to work in 2.0.2 just as well as it did in 2.0.1.

I think the semantically most correct way to fix this, would be to to give `errorhandler` a type smilar to `Callable[[SomeOtherGenericException], Callable[[ErrorHandlerCallable[GenericException]], ErrorHandlerCallable[GenericException]]` where `SomeOtherGenericException` would be a type variable that would always need to be a subtype of `GenericException`, but I am not sure if Python's type system can express relations between type variables like that.

Environment:

- Python version: 3.9.7
- Flask version: 2.0.2

**Comment by davidism** [comment]
This seems almost identical to https://github.com/pallets/flask/issues/4295. Please check if the linked PR works here too, otherwise I'm happy to review another PR.

**Comment by Rohan-Salwan** [comment]
Hello @Kritzefitz,
Instead of using Scaffold class methods directly, try to use Blueprint class methods.
Here's the sample code of  the Blueprint class  usage where I used method app_errorhandler 
which solved your issue so take a look: https://github.com/Rohan-Salwan/RANDOM/blob/b984f5e22ef4a9c5c060ad346765a7a053f21f59/app.py#L1-L15

For more details, please refer to this documentation link: https://flask.palletsprojects.com/en/2.0.x/api/?highlight=blueprint%20app_errorhandler#flask.Blueprint.app_errorhandler

@davidism please review and let me know if I am missing something.

**Comment by ThiefMaster** [comment]
@Rohan-Salwan what does this have to do with the user's mypy errors?

**Comment by davidism** [comment]
It doesn't appear possible to fix both this and #4097 (matching decorator argument type to function argument type) at the same time.
