### ISSUE TITLE
AttributeError: 'DispatchingApp' object has no attribute 'config'

### ISSUE THREAD

**Issue by laerus** [pallets/flask#2005]
going through the tutorial on latest master, this exception is raised on `flask run`
(running inside a virtualenv)
```
>>> flask --version
Flask 0.11.2-dev
Python 3.5.2+ (default, Aug  5 2016, 08:07:14) 
[GCC 6.1.1 20160724]
>>> which -v flask
/home/laerus/.venvs/flask/bin/flask (from PATH element 0)
>>> flask run
 * Serving Flask app "flaskr"
 * Forcing debug mode off
Traceback (most recent call last):
  File "/home/laerus/.venvs/flask/bin/flask", line 9, in <module>
    load_entry_point('Flask==0.11.2.dev0', 'console_scripts', 'flask')()
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/flask/cli.py", line 508, in main
    cli.main(args=args, prog_name=name)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/flask/cli.py", line 374, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/laerus/.venvs/flask/lib/python3.5/site-packages/flask/cli.py", line 433, in run_command
    passthrough_errors=app.config['PROPAGATE_EXCEPTIONS'])
AttributeError: 'DispatchingApp' object has no attribute 'config'
```

**Comment by laerus** [comment]
git bisect points to 098ea0c8ca3b2f3c6715b1048bec6a42db6298e1
