### ISSUE TITLE
TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by OliverSparrow** [pallets/flask#4502]
## Synopsis

TypeErrors referencing the `entry_points()` method were raised, while running Flask projects initially written for Version 2.0.1. The error does not seem to be a user-programming mistake, as the error was seen when running the Tutorial Project provided in the Flask Documentation.

## Programming Environment

The referenced Tutorial project is found in the following documentation: https://flask.palletsprojects.com/en/2.0.x/tutorial/
Minor corrections were made to the `__init__` file to mirror the Tutorial file in v2.1.0.

### Environment:
- Python version: 3.7.4
- Flask version: 2.0.1
- OS: MacOS High Sierra

## Error Statement
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/cli.py", line 985, in main
    cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/cli.py", line 522, in get_command
    self._load_plugin_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/cli.py", line 516, in _load_plugin_commands
    for ep in metadata.entry_points(group="flask.commands"):
TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Comment by YiSang665** [comment]
@OliverSparrow  its not so clear what you did:
hello.py
```
from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello():
    return 'Hello, World!'

```
then
```
FLASK_APP=hello:app flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app 'hello:app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)

```
python3.10 in my case, so can you describe full example of your code that was crashed ?

**Comment by OliverSparrow** [comment]
Put simply, the code that had trouble running was the Flaskr blogging application tutorial on the Flask Documentations, a few pages AFTER the Hello World documentation. Sorry for not specifying earlier...

After downgrading the Flask version to 2.0.1 again, the application works just fine.
Since v2.1.0 dropped support for Python 3.6, would this cause issues when running it on Python 3.7?

PS. Should I display the code for all parts of the projects, including associated Blueprints & Views?

**Comment by OliverSparrow** [comment]
The code works in Flask v2.0.1, although I haven't tested it for 2.0.2 or 2.0.3 yet.

The tested code snippet:
```
import os

from flask import Flask


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello, World!'

    return app
```

When looking at the Traceback statement, the error seemed to originate from Flask's CLI module. Specifically, the error was triggered by the following code snippet.
```
        for ep in metadata.entry_points(group="flask.commands"):
            self.add_command(ep.load(), ep.name)
```
Does Python 3.7 support importlib.metadata?

**Comment by theasaurus** [comment]
Hi,
This is related to the change from Flask using `pkg_resources` to using `importlib.metadata`. If your `importlib.metadata` is out of date, you will get that error. See [https://github.com/mkdocs/mkdocs/issues/2469](https://github.com/mkdocs/mkdocs/issues/2469) for a similar issue. Updating `importlib.metadata` to the latest version seems to fix this bug!

**Comment by OliverSparrow** [comment]
@theasaurus  After looking through the installed libraries, it turns out that my ``importlib-metadata`` library was out-of-date, at v1.6.1. After upgrading it manually to v4.11.3, Flask seems to work again!

Apparently this is an issue dealt by people who use the PIP package manager, since even after upgrading or reinstalling Flask v2.1.0, importlib-metadata would not update.

**Comment by davidism** [comment]
I'll add a minimum version for the dependency on importlib_metadata so that a version that supports this API is installed. Note that importlib_metadata is only used on Python < 3.10, so you can also avoid this by upgrading to the latest Python.
