### ISSUE TITLE
PR #4283 broke traceback on import errors.

### ISSUE THREAD

**Issue by Tyskiep99** [pallets/flask#4434]
When using flask 2.0.2 and having an error in the import the flask cli does not output the traceback anymore.
It seems to have stopped to work after https://github.com/pallets/flask/pull/4283 was merged.

To reproduce: make an import error and run:
```
(.venv) PS D:\Workspace\private\notifications\python-api> flask run --debugger --reload
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'wsgi', an ImportError was raised.
```

Expected the following traceback:
```(.venv) PS D:\Workspace\private\notifications\python-api> python
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gna import create_app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Workspace\private\notifications\python-api\gna\__init__.py", line 4, in <module>
    from . import models, routes, services
  File "D:\Workspace\private\notifications\python-api\gna\routes\__init__.py", line 4, in <module>
    from .api import api_bp
ImportError: cannot import name 'api_bp' from 'gna.routes.api' (D:\Workspace\private\notifications\python-api\gna\routes\api\__init__.py)
>>>
```

Environment:

- Python version: 3.10.2
- Flask version: 2.0.2

**Comment by Tyskiep99** [comment]
The fix has been re-introduced with https://github.com/pallets/flask/commit/e679a85b80df354f8632f8ab3e40135f16f5e6d0#diff-fed8939d1905b99bba605ad91e9ccdf5ede6223e03ccbc3f0121853035051e62
already in master, when do you plan a new release ?

**Comment by davidism** [comment]
Duplicate of #4307

**Comment by Tyskiep99** [comment]
Any idea on the new release tho? cause its not really deployed yet

**Comment by Edmartt** [comment]
Always saying "duplicate x" or something like that, but the issue is still here...
